FROM bash:5.2
RUN apk add --no-cache openssl || (apt-get update && apt-get install -y openssl)
COPY ./setup-scripts /workspace/scripts
COPY ./deploy /workspace/deploy
RUN mkdir -p /certs && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /certs/local.key -out /certs/local.crt -subj "/CN=localhost"